app1/urls.py
from app1.views import *
from django.urls import path
app_name='sumi'
urlpatterns=[
    path('sumi/',sumi,name='sumi'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('ichika/',ichika,name='ichika'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sumi(request):
    return render(request,'sumi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def ichika(request):
    return render(request,'ichika.html')

templates/ichika.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> ichika is a small girl</h1>
        <a href="{% url 'sumi:sumi' %}">Don't Click</a>
        
    </center>
    
</body>
</html>

templates/sumi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>She Is A Dangerous Girl</h1>
        <h1>But She Don't Know About Dangerous</h1>
        <a href="{% url 'nothing:ichika' %}"> good girl </a>
    </center>
    
</body>
</html>